# Generated by Django 4.1.13 on 2024-09-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatresponse',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
